// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ProtocolLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ProtocolLib",
  "sourceName": "contracts/libraries/ProtocolLib.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212203c89c5da658b407d7ac0dc6e8a7bb80f8cf96a411065a288b802f9a4deb0b37a64736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212203c89c5da658b407d7ac0dc6e8a7bb80f8cf96a411065a288b802f9a4deb0b37a64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ProtocolLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ProtocolLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/ProtocolLib.sol:ProtocolLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ProtocolLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ProtocolLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ProtocolLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/ProtocolLib.sol:ProtocolLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ProtocolLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ProtocolLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ProtocolLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/ProtocolLib.sol:ProtocolLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ProtocolLib$Type["abi"]>>;
}
