// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Types256$Type } from "./Types256";
import { Types64$Type } from "./Types64";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Types256"]: Types256$Type;
    ["Types64"]: Types64$Type;
    ["contracts/libraries/Types.sol:Types256"]: Types256$Type;
    ["contracts/libraries/Types.sol:Types64"]: Types64$Type;
  }

  interface ContractTypesMap {
    ["Types256"]: GetContractReturnType<Types256$Type["abi"]>;
    ["Types64"]: GetContractReturnType<Types64$Type["abi"]>;
    ["contracts/libraries/Types.sol:Types256"]: GetContractReturnType<Types256$Type["abi"]>;
    ["contracts/libraries/Types.sol:Types64"]: GetContractReturnType<Types64$Type["abi"]>;
  }
}
