/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SSVClusters } from "./SSVClusters";
export type { SSVDAO } from "./SSVDAO";
export type { SSVOperators } from "./SSVOperators";
export type { SSVOperatorsWhitelist } from "./SSVOperatorsWhitelist";
export type { SSVViews } from "./SSVViews";
