// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSVNetworkViews$Type } from "./SSVNetworkViews";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSVNetworkViews"]: SSVNetworkViews$Type;
    ["contracts/SSVNetworkViews.sol:SSVNetworkViews"]: SSVNetworkViews$Type;
  }

  interface ContractTypesMap {
    ["SSVNetworkViews"]: GetContractReturnType<SSVNetworkViews$Type["abi"]>;
    ["contracts/SSVNetworkViews.sol:SSVNetworkViews"]: GetContractReturnType<SSVNetworkViews$Type["abi"]>;
  }
}
