// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ClusterLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ClusterLib",
  "sourceName": "contracts/libraries/ClusterLib.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220fec9af5b7788a561b996b27f39adc5b4a2422f632b334e85306178e156d730d664736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220fec9af5b7788a561b996b27f39adc5b4a2422f632b334e85306178e156d730d664736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ClusterLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ClusterLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/ClusterLib.sol:ClusterLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ClusterLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ClusterLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ClusterLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/ClusterLib.sol:ClusterLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ClusterLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ClusterLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ClusterLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/ClusterLib.sol:ClusterLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ClusterLib$Type["abi"]>>;
}
