// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AttackerContract$Type } from "./AttackerContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AttackerContract"]: AttackerContract$Type;
    ["contracts/test/mocks/AttackerWhitelistingContract.sol:AttackerContract"]: AttackerContract$Type;
  }

  interface ContractTypesMap {
    ["AttackerContract"]: GetContractReturnType<AttackerContract$Type["abi"]>;
    ["contracts/test/mocks/AttackerWhitelistingContract.sol:AttackerContract"]: GetContractReturnType<AttackerContract$Type["abi"]>;
  }
}
