// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CoreLibT$Type } from "./CoreLibT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CoreLibT"]: CoreLibT$Type;
    ["contracts/test/libraries/CoreLibT.sol:CoreLibT"]: CoreLibT$Type;
  }

  interface ContractTypesMap {
    ["CoreLibT"]: GetContractReturnType<CoreLibT$Type["abi"]>;
    ["contracts/test/libraries/CoreLibT.sol:CoreLibT"]: GetContractReturnType<CoreLibT$Type["abi"]>;
  }
}
