// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CoreLibT$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CoreLibT",
  "sourceName": "contracts/test/libraries/CoreLibT.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122079246dcea150f32ad81948d32338107d938c5dd7dd4f2ad951dc6641679c0ea464736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122079246dcea150f32ad81948d32338107d938c5dd7dd4f2ad951dc6641679c0ea464736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "CoreLibT",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibT$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/test/libraries/CoreLibT.sol:CoreLibT",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLibT$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "CoreLibT",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibT$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/test/libraries/CoreLibT.sol:CoreLibT",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLibT$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "CoreLibT",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibT$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/test/libraries/CoreLibT.sol:CoreLibT",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLibT$Type["abi"]>>;
}
