// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SSVStorageT$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SSVStorageT",
  "sourceName": "contracts/test/libraries/SSVStorageT.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "enum SSVModules",
          "name": "moduleId",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "moduleAddress",
          "type": "address"
        }
      ],
      "name": "ModuleUpgraded",
      "type": "event"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122016f64ff39419be2488db9f4984dc05122a20b19ec39a171be7b09a96f175e90664736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122016f64ff39419be2488db9f4984dc05122a20b19ec39a171be7b09a96f175e90664736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SSVStorageT",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SSVStorageT$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/test/libraries/SSVStorageT.sol:SSVStorageT",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SSVStorageT$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SSVStorageT",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SSVStorageT$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/test/libraries/SSVStorageT.sol:SSVStorageT",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SSVStorageT$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SSVStorageT",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SSVStorageT$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/test/libraries/SSVStorageT.sol:SSVStorageT",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SSVStorageT$Type["abi"]>>;
}
