// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ValidatorLib$Type } from "./ValidatorLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ValidatorLib"]: ValidatorLib$Type;
    ["contracts/libraries/ValidatorLib.sol:ValidatorLib"]: ValidatorLib$Type;
  }

  interface ContractTypesMap {
    ["ValidatorLib"]: GetContractReturnType<ValidatorLib$Type["abi"]>;
    ["contracts/libraries/ValidatorLib.sol:ValidatorLib"]: GetContractReturnType<ValidatorLib$Type["abi"]>;
  }
}
