// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ValidatorLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ValidatorLib",
  "sourceName": "contracts/libraries/ValidatorLib.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122052c205cb1d7829245613f0cd5999f67132e4b5ce68439c525f7ef67ff96f239d64736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122052c205cb1d7829245613f0cd5999f67132e4b5ce68439c525f7ef67ff96f239d64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ValidatorLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ValidatorLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/ValidatorLib.sol:ValidatorLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ValidatorLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ValidatorLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ValidatorLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/ValidatorLib.sol:ValidatorLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ValidatorLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ValidatorLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ValidatorLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/ValidatorLib.sol:ValidatorLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ValidatorLib$Type["abi"]>>;
}
