// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BasicWhitelisting$Type } from "./BasicWhitelisting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BasicWhitelisting"]: BasicWhitelisting$Type;
    ["contracts/whitelisting/BasicWhitelisting.sol:BasicWhitelisting"]: BasicWhitelisting$Type;
  }

  interface ContractTypesMap {
    ["BasicWhitelisting"]: GetContractReturnType<BasicWhitelisting$Type["abi"]>;
    ["contracts/whitelisting/BasicWhitelisting.sol:BasicWhitelisting"]: GetContractReturnType<BasicWhitelisting$Type["abi"]>;
  }
}
