// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSVDAO$Type } from "./SSVDAO";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSVDAO"]: SSVDAO$Type;
    ["contracts/modules/SSVDAO.sol:SSVDAO"]: SSVDAO$Type;
  }

  interface ContractTypesMap {
    ["SSVDAO"]: GetContractReturnType<SSVDAO$Type["abi"]>;
    ["contracts/modules/SSVDAO.sol:SSVDAO"]: GetContractReturnType<SSVDAO$Type["abi"]>;
  }
}
