// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Ownable2StepUpgradeable$Type } from "./Ownable2StepUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Ownable2StepUpgradeable"]: Ownable2StepUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/access/Ownable2StepUpgradeable.sol:Ownable2StepUpgradeable"]: Ownable2StepUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["Ownable2StepUpgradeable"]: GetContractReturnType<Ownable2StepUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/access/Ownable2StepUpgradeable.sol:Ownable2StepUpgradeable"]: GetContractReturnType<Ownable2StepUpgradeable$Type["abi"]>;
  }
}
