// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AddressUpgradeable$Type } from "./AddressUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AddressUpgradeable"]: AddressUpgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol:AddressUpgradeable"]: AddressUpgradeable$Type;
  }

  interface ContractTypesMap {
    ["AddressUpgradeable"]: GetContractReturnType<AddressUpgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol:AddressUpgradeable"]: GetContractReturnType<AddressUpgradeable$Type["abi"]>;
  }
}
