// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BeneficiaryContract$Type } from "./BeneficiaryContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BeneficiaryContract"]: BeneficiaryContract$Type;
    ["contracts/test/mocks/BeneficiaryContract.sol:BeneficiaryContract"]: BeneficiaryContract$Type;
  }

  interface ContractTypesMap {
    ["BeneficiaryContract"]: GetContractReturnType<BeneficiaryContract$Type["abi"]>;
    ["contracts/test/mocks/BeneficiaryContract.sol:BeneficiaryContract"]: GetContractReturnType<BeneficiaryContract$Type["abi"]>;
  }
}
