// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSVToken$Type } from "./SSVToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSVToken"]: SSVToken$Type;
    ["contracts/token/SSVToken.sol:SSVToken"]: SSVToken$Type;
  }

  interface ContractTypesMap {
    ["SSVToken"]: GetContractReturnType<SSVToken$Type["abi"]>;
    ["contracts/token/SSVToken.sol:SSVToken"]: GetContractReturnType<SSVToken$Type["abi"]>;
  }
}
