// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSVNetworkUpgrade$Type } from "./SSVNetworkUpgrade";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSVNetworkUpgrade"]: SSVNetworkUpgrade$Type;
    ["contracts/test/SSVNetworkUpgrade.sol:SSVNetworkUpgrade"]: SSVNetworkUpgrade$Type;
  }

  interface ContractTypesMap {
    ["SSVNetworkUpgrade"]: GetContractReturnType<SSVNetworkUpgrade$Type["abi"]>;
    ["contracts/test/SSVNetworkUpgrade.sol:SSVNetworkUpgrade"]: GetContractReturnType<SSVNetworkUpgrade$Type["abi"]>;
  }
}
