/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as external from "./external";
export type { external };
export type { ISSVClusters } from "./ISSVClusters";
export type { ISSVDAO } from "./ISSVDAO";
export type { ISSVNetwork } from "./ISSVNetwork";
export type { ISSVNetworkCore } from "./ISSVNetworkCore";
export type { ISSVOperators } from "./ISSVOperators";
export type { ISSVOperatorsWhitelist } from "./ISSVOperatorsWhitelist";
export type { ISSVViews } from "./ISSVViews";
