// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISSVNetwork$Type } from "./ISSVNetwork";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISSVNetwork"]: ISSVNetwork$Type;
    ["contracts/interfaces/ISSVNetwork.sol:ISSVNetwork"]: ISSVNetwork$Type;
  }

  interface ContractTypesMap {
    ["ISSVNetwork"]: GetContractReturnType<ISSVNetwork$Type["abi"]>;
    ["contracts/interfaces/ISSVNetwork.sol:ISSVNetwork"]: GetContractReturnType<ISSVNetwork$Type["abi"]>;
  }
}
