// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CoreLib$Type } from "./CoreLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CoreLib"]: CoreLib$Type;
    ["contracts/libraries/CoreLib.sol:CoreLib"]: CoreLib$Type;
  }

  interface ContractTypesMap {
    ["CoreLib"]: GetContractReturnType<CoreLib$Type["abi"]>;
    ["contracts/libraries/CoreLib.sol:CoreLib"]: GetContractReturnType<CoreLib$Type["abi"]>;
  }
}
