// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface CoreLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "CoreLib",
  "sourceName": "contracts/libraries/CoreLib.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "enum SSVModules",
          "name": "moduleId",
          "type": "uint8"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "moduleAddress",
          "type": "address"
        }
      ],
      "name": "ModuleUpgraded",
      "type": "event"
    }
  ],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122087262d83843d897fca5b2f0c36d9fd4e3b1179c1a7fedbd34853dae6fff0103864736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122087262d83843d897fca5b2f0c36d9fd4e3b1179c1a7fedbd34853dae6fff0103864736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "contracts/libraries/CoreLib.sol:CoreLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<CoreLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/CoreLib.sol:CoreLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<CoreLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "contracts/libraries/CoreLib.sol:CoreLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<CoreLib$Type["abi"]>>;
}
