// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC165Checker$Type } from "./ERC165Checker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC165Checker"]: ERC165Checker$Type;
    ["@openzeppelin/contracts/utils/introspection/ERC165Checker.sol:ERC165Checker"]: ERC165Checker$Type;
  }

  interface ContractTypesMap {
    ["ERC165Checker"]: GetContractReturnType<ERC165Checker$Type["abi"]>;
    ["@openzeppelin/contracts/utils/introspection/ERC165Checker.sol:ERC165Checker"]: GetContractReturnType<ERC165Checker$Type["abi"]>;
  }
}
