// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Counters$Type } from "./Counters";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Counters"]: Counters$Type;
    ["@openzeppelin/contracts/utils/Counters.sol:Counters"]: Counters$Type;
  }

  interface ContractTypesMap {
    ["Counters"]: GetContractReturnType<Counters$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Counters.sol:Counters"]: GetContractReturnType<Counters$Type["abi"]>;
  }
}
