// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC1967Upgradeable$Type } from "./IERC1967Upgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC1967Upgradeable"]: IERC1967Upgradeable$Type;
    ["@openzeppelin/contracts-upgradeable/interfaces/IERC1967Upgradeable.sol:IERC1967Upgradeable"]: IERC1967Upgradeable$Type;
  }

  interface ContractTypesMap {
    ["IERC1967Upgradeable"]: GetContractReturnType<IERC1967Upgradeable$Type["abi"]>;
    ["@openzeppelin/contracts-upgradeable/interfaces/IERC1967Upgradeable.sol:IERC1967Upgradeable"]: GetContractReturnType<IERC1967Upgradeable$Type["abi"]>;
  }
}
