/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISSVDAO,
  ISSVDAOInterface,
} from "../../../../hardhat/contracts/interfaces/ISSVDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "AddressIsWhitelistingContract",
    type: "error",
  },
  {
    inputs: [],
    name: "ApprovalNotWithinTimeframe",
    type: "error",
  },
  {
    inputs: [],
    name: "CallerNotOwner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "CallerNotOwnerWithData",
    type: "error",
  },
  {
    inputs: [],
    name: "CallerNotWhitelisted",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "operatorId",
        type: "uint64",
      },
    ],
    name: "CallerNotWhitelistedWithData",
    type: "error",
  },
  {
    inputs: [],
    name: "ClusterAlreadyEnabled",
    type: "error",
  },
  {
    inputs: [],
    name: "ClusterDoesNotExists",
    type: "error",
  },
  {
    inputs: [],
    name: "ClusterIsLiquidated",
    type: "error",
  },
  {
    inputs: [],
    name: "ClusterNotLiquidatable",
    type: "error",
  },
  {
    inputs: [],
    name: "EmptyPublicKeysList",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "operatorId",
        type: "uint64",
      },
    ],
    name: "ExceedValidatorLimit",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "operatorId",
        type: "uint64",
      },
    ],
    name: "ExceedValidatorLimitWithData",
    type: "error",
  },
  {
    inputs: [],
    name: "FeeExceedsIncreaseLimit",
    type: "error",
  },
  {
    inputs: [],
    name: "FeeIncreaseNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "FeeTooHigh",
    type: "error",
  },
  {
    inputs: [],
    name: "FeeTooLow",
    type: "error",
  },
  {
    inputs: [],
    name: "IncorrectClusterState",
    type: "error",
  },
  {
    inputs: [],
    name: "IncorrectValidatorState",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "publicKey",
        type: "bytes",
      },
    ],
    name: "IncorrectValidatorStateWithData",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidContractAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidOperatorIdsLength",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidPublicKeyLength",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidWhitelistAddressesLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "InvalidWhitelistingContract",
    type: "error",
  },
  {
    inputs: [],
    name: "MaxValueExceeded",
    type: "error",
  },
  {
    inputs: [],
    name: "NewBlockPeriodIsBelowMinimum",
    type: "error",
  },
  {
    inputs: [],
    name: "NoFeeDeclared",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAuthorized",
    type: "error",
  },
  {
    inputs: [],
    name: "OperatorAlreadyExists",
    type: "error",
  },
  {
    inputs: [],
    name: "OperatorDoesNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "OperatorsListNotUnique",
    type: "error",
  },
  {
    inputs: [],
    name: "PublicKeysSharesLengthMismatch",
    type: "error",
  },
  {
    inputs: [],
    name: "SameFeeChangeNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "TargetModuleDoesNotExist",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "moduleId",
        type: "uint8",
      },
    ],
    name: "TargetModuleDoesNotExistWithData",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "UnsortedOperatorsList",
    type: "error",
  },
  {
    inputs: [],
    name: "ValidatorAlreadyExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "publicKey",
        type: "bytes",
      },
    ],
    name: "ValidatorAlreadyExistsWithData",
    type: "error",
  },
  {
    inputs: [],
    name: "ValidatorDoesNotExist",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddressNotAllowed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "value",
        type: "uint64",
      },
    ],
    name: "DeclareOperatorFeePeriodUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "value",
        type: "uint64",
      },
    ],
    name: "ExecuteOperatorFeePeriodUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "value",
        type: "uint64",
      },
    ],
    name: "LiquidationThresholdPeriodUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "MinimumLiquidationCollateralUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "NetworkEarningsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldFee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newFee",
        type: "uint256",
      },
    ],
    name: "NetworkFeeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "value",
        type: "uint64",
      },
    ],
    name: "OperatorFeeIncreaseLimitUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "maxFee",
        type: "uint64",
      },
    ],
    name: "OperatorMaximumFeeUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "timeInSeconds",
        type: "uint64",
      },
    ],
    name: "updateDeclareOperatorFeePeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "timeInSeconds",
        type: "uint64",
      },
    ],
    name: "updateExecuteOperatorFeePeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "blocks",
        type: "uint64",
      },
    ],
    name: "updateLiquidationThresholdPeriod",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "maxFee",
        type: "uint64",
      },
    ],
    name: "updateMaximumOperatorFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "updateMinimumLiquidationCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "updateNetworkFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "percentage",
        type: "uint64",
      },
    ],
    name: "updateOperatorFeeIncreaseLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawNetworkEarnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISSVDAO__factory {
  static readonly abi = _abi;
  static createInterface(): ISSVDAOInterface {
    return new Interface(_abi) as ISSVDAOInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISSVDAO {
    return new Contract(address, _abi, runner) as unknown as ISSVDAO;
  }
}
