/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ISSVNetworkTInterface extends Interface {
  getFunction(
    nameOrSignature: "initialize" | "setFeeRecipientAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipientAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipientAddress",
    data: BytesLike
  ): Result;
}

export interface ISSVNetworkT extends BaseContract {
  connect(runner?: ContractRunner | null): ISSVNetworkT;
  waitForDeployment(): Promise<this>;

  interface: ISSVNetworkTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  initialize: TypedContractMethod<
    [
      token_: AddressLike,
      ssvOperators_: AddressLike,
      ssvClusters_: AddressLike,
      ssvDAO_: AddressLike,
      ssvViews_: AddressLike,
      minimumBlocksBeforeLiquidation_: BigNumberish,
      minimumLiquidationCollateral_: BigNumberish,
      validatorsPerOperatorLimit_: BigNumberish,
      declareOperatorFeePeriod_: BigNumberish,
      executeOperatorFeePeriod_: BigNumberish,
      operatorMaxFeeIncrease_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setFeeRecipientAddress: TypedContractMethod<
    [feeRecipientAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      token_: AddressLike,
      ssvOperators_: AddressLike,
      ssvClusters_: AddressLike,
      ssvDAO_: AddressLike,
      ssvViews_: AddressLike,
      minimumBlocksBeforeLiquidation_: BigNumberish,
      minimumLiquidationCollateral_: BigNumberish,
      validatorsPerOperatorLimit_: BigNumberish,
      declareOperatorFeePeriod_: BigNumberish,
      executeOperatorFeePeriod_: BigNumberish,
      operatorMaxFeeIncrease_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRecipientAddress"
  ): TypedContractMethod<
    [feeRecipientAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
