// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RegisterAuth$Type } from "./RegisterAuth";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RegisterAuth"]: RegisterAuth$Type;
    ["contracts/deprecated/RegisterAuth.sol:RegisterAuth"]: RegisterAuth$Type;
  }

  interface ContractTypesMap {
    ["RegisterAuth"]: GetContractReturnType<RegisterAuth$Type["abi"]>;
    ["contracts/deprecated/RegisterAuth.sol:RegisterAuth"]: GetContractReturnType<RegisterAuth$Type["abi"]>;
  }
}
