/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface BeneficiaryContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "registerOperator"
      | "setTargetOperatorId"
      | "withdrawOperatorEarnings"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "registerOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetOperatorId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOperatorEarnings",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "registerOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetOperatorId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOperatorEarnings",
    data: BytesLike
  ): Result;
}

export interface BeneficiaryContract extends BaseContract {
  connect(runner?: ContractRunner | null): BeneficiaryContract;
  waitForDeployment(): Promise<this>;

  interface: BeneficiaryContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  registerOperator: TypedContractMethod<[], [bigint], "nonpayable">;

  setTargetOperatorId: TypedContractMethod<
    [_operatorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawOperatorEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "registerOperator"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setTargetOperatorId"
  ): TypedContractMethod<[_operatorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawOperatorEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  filters: {};
}
