/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace ISSVNetworkCore {
  export type ClusterStruct = {
    validatorCount: BigNumberish;
    networkFeeIndex: BigNumberish;
    index: BigNumberish;
    active: boolean;
    balance: BigNumberish;
  };

  export type ClusterStructOutput = [
    validatorCount: bigint,
    networkFeeIndex: bigint,
    index: bigint,
    active: boolean,
    balance: bigint
  ] & {
    validatorCount: bigint;
    networkFeeIndex: bigint;
    index: bigint;
    active: boolean;
    balance: bigint;
  };
}

export interface GenericWhitelistContractInterface extends Interface {
  getFunction(nameOrSignature: "registerValidatorSSV"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "registerValidatorSSV",
    values: [
      BytesLike,
      BigNumberish[],
      BytesLike,
      BigNumberish,
      ISSVNetworkCore.ClusterStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "registerValidatorSSV",
    data: BytesLike
  ): Result;
}

export interface GenericWhitelistContract extends BaseContract {
  connect(runner?: ContractRunner | null): GenericWhitelistContract;
  waitForDeployment(): Promise<this>;

  interface: GenericWhitelistContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  registerValidatorSSV: TypedContractMethod<
    [
      _publicKey: BytesLike,
      _operatorIds: BigNumberish[],
      _sharesData: BytesLike,
      _amount: BigNumberish,
      _cluserData: ISSVNetworkCore.ClusterStruct
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "registerValidatorSSV"
  ): TypedContractMethod<
    [
      _publicKey: BytesLike,
      _operatorIds: BigNumberish[],
      _sharesData: BytesLike,
      _amount: BigNumberish,
      _cluserData: ISSVNetworkCore.ClusterStruct
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
