/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attackerWhitelistingContractSol from "./AttackerWhitelistingContract.sol";
export type { attackerWhitelistingContractSol };
export type { BadOperatorWhitelistingContract } from "./BadOperatorWhitelistingContract";
export type { BeneficiaryContract } from "./BeneficiaryContract";
export type { FakeWhitelistingContract } from "./FakeWhitelistingContract";
export type { GenericWhitelistContract } from "./GenericWhitelistContract";
export type { MockWhitelistingContract } from "./MockWhitelistingContract";
