// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISSVOperators$Type } from "./ISSVOperators";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISSVOperators"]: ISSVOperators$Type;
    ["contracts/interfaces/ISSVOperators.sol:ISSVOperators"]: ISSVOperators$Type;
  }

  interface ContractTypesMap {
    ["ISSVOperators"]: GetContractReturnType<ISSVOperators$Type["abi"]>;
    ["contracts/interfaces/ISSVOperators.sol:ISSVOperators"]: GetContractReturnType<ISSVOperators$Type["abi"]>;
  }
}
