// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISSVViews$Type } from "./ISSVViews";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISSVViews"]: ISSVViews$Type;
    ["contracts/interfaces/ISSVViews.sol:ISSVViews"]: ISSVViews$Type;
  }

  interface ContractTypesMap {
    ["ISSVViews"]: GetContractReturnType<ISSVViews$Type["abi"]>;
    ["contracts/interfaces/ISSVViews.sol:ISSVViews"]: GetContractReturnType<ISSVViews$Type["abi"]>;
  }
}
