// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSVClusters$Type } from "./SSVClusters";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSVClusters"]: SSVClusters$Type;
    ["contracts/modules/SSVClusters.sol:SSVClusters"]: SSVClusters$Type;
  }

  interface ContractTypesMap {
    ["SSVClusters"]: GetContractReturnType<SSVClusters$Type["abi"]>;
    ["contracts/modules/SSVClusters.sol:SSVClusters"]: GetContractReturnType<SSVClusters$Type["abi"]>;
  }
}
