// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISSVNetworkCore$Type } from "./ISSVNetworkCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISSVNetworkCore"]: ISSVNetworkCore$Type;
    ["contracts/interfaces/ISSVNetworkCore.sol:ISSVNetworkCore"]: ISSVNetworkCore$Type;
  }

  interface ContractTypesMap {
    ["ISSVNetworkCore"]: GetContractReturnType<ISSVNetworkCore$Type["abi"]>;
    ["contracts/interfaces/ISSVNetworkCore.sol:ISSVNetworkCore"]: GetContractReturnType<ISSVNetworkCore$Type["abi"]>;
  }
}
