// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SSVNetworkUpgradeValidatorsPerOperator$Type } from "./SSVNetworkUpgradeValidatorsPerOperator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SSVNetworkUpgradeValidatorsPerOperator"]: SSVNetworkUpgradeValidatorsPerOperator$Type;
    ["contracts/upgrades/stage/holesky/SSVNetworkUpgradeValidatorsPerOperator.sol:SSVNetworkUpgradeValidatorsPerOperator"]: SSVNetworkUpgradeValidatorsPerOperator$Type;
  }

  interface ContractTypesMap {
    ["SSVNetworkUpgradeValidatorsPerOperator"]: GetContractReturnType<SSVNetworkUpgradeValidatorsPerOperator$Type["abi"]>;
    ["contracts/upgrades/stage/holesky/SSVNetworkUpgradeValidatorsPerOperator.sol:SSVNetworkUpgradeValidatorsPerOperator"]: GetContractReturnType<SSVNetworkUpgradeValidatorsPerOperator$Type["abi"]>;
  }
}
