export var Account_OrderBy;
(function (Account_OrderBy) {
    Account_OrderBy["Clusters"] = "clusters";
    Account_OrderBy["FeeRecipient"] = "feeRecipient";
    Account_OrderBy["Id"] = "id";
    Account_OrderBy["Nonce"] = "nonce";
    Account_OrderBy["Operators"] = "operators";
    Account_OrderBy["ValidatorCount"] = "validatorCount";
    Account_OrderBy["Validators"] = "validators";
})(Account_OrderBy || (Account_OrderBy = {}));
export var Aggregation_Interval;
(function (Aggregation_Interval) {
    Aggregation_Interval["Day"] = "day";
    Aggregation_Interval["Hour"] = "hour";
})(Aggregation_Interval || (Aggregation_Interval = {}));
export var ClusterDeposited_OrderBy;
(function (ClusterDeposited_OrderBy) {
    ClusterDeposited_OrderBy["BlockNumber"] = "blockNumber";
    ClusterDeposited_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ClusterDeposited_OrderBy["ClusterActive"] = "cluster_active";
    ClusterDeposited_OrderBy["ClusterBalance"] = "cluster_balance";
    ClusterDeposited_OrderBy["ClusterIndex"] = "cluster_index";
    ClusterDeposited_OrderBy["ClusterNetworkFeeIndex"] = "cluster_networkFeeIndex";
    ClusterDeposited_OrderBy["ClusterValidatorCount"] = "cluster_validatorCount";
    ClusterDeposited_OrderBy["Id"] = "id";
    ClusterDeposited_OrderBy["OperatorIds"] = "operatorIds";
    ClusterDeposited_OrderBy["Owner"] = "owner";
    ClusterDeposited_OrderBy["TransactionHash"] = "transactionHash";
    ClusterDeposited_OrderBy["Value"] = "value";
})(ClusterDeposited_OrderBy || (ClusterDeposited_OrderBy = {}));
export var ClusterLiquidated_OrderBy;
(function (ClusterLiquidated_OrderBy) {
    ClusterLiquidated_OrderBy["BlockNumber"] = "blockNumber";
    ClusterLiquidated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ClusterLiquidated_OrderBy["ClusterActive"] = "cluster_active";
    ClusterLiquidated_OrderBy["ClusterBalance"] = "cluster_balance";
    ClusterLiquidated_OrderBy["ClusterIndex"] = "cluster_index";
    ClusterLiquidated_OrderBy["ClusterNetworkFeeIndex"] = "cluster_networkFeeIndex";
    ClusterLiquidated_OrderBy["ClusterValidatorCount"] = "cluster_validatorCount";
    ClusterLiquidated_OrderBy["Id"] = "id";
    ClusterLiquidated_OrderBy["OperatorIds"] = "operatorIds";
    ClusterLiquidated_OrderBy["Owner"] = "owner";
    ClusterLiquidated_OrderBy["TransactionHash"] = "transactionHash";
})(ClusterLiquidated_OrderBy || (ClusterLiquidated_OrderBy = {}));
export var ClusterReactivated_OrderBy;
(function (ClusterReactivated_OrderBy) {
    ClusterReactivated_OrderBy["BlockNumber"] = "blockNumber";
    ClusterReactivated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ClusterReactivated_OrderBy["ClusterActive"] = "cluster_active";
    ClusterReactivated_OrderBy["ClusterBalance"] = "cluster_balance";
    ClusterReactivated_OrderBy["ClusterIndex"] = "cluster_index";
    ClusterReactivated_OrderBy["ClusterNetworkFeeIndex"] = "cluster_networkFeeIndex";
    ClusterReactivated_OrderBy["ClusterValidatorCount"] = "cluster_validatorCount";
    ClusterReactivated_OrderBy["Id"] = "id";
    ClusterReactivated_OrderBy["OperatorIds"] = "operatorIds";
    ClusterReactivated_OrderBy["Owner"] = "owner";
    ClusterReactivated_OrderBy["TransactionHash"] = "transactionHash";
})(ClusterReactivated_OrderBy || (ClusterReactivated_OrderBy = {}));
export var ClusterWithdrawn_OrderBy;
(function (ClusterWithdrawn_OrderBy) {
    ClusterWithdrawn_OrderBy["BlockNumber"] = "blockNumber";
    ClusterWithdrawn_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ClusterWithdrawn_OrderBy["ClusterActive"] = "cluster_active";
    ClusterWithdrawn_OrderBy["ClusterBalance"] = "cluster_balance";
    ClusterWithdrawn_OrderBy["ClusterIndex"] = "cluster_index";
    ClusterWithdrawn_OrderBy["ClusterNetworkFeeIndex"] = "cluster_networkFeeIndex";
    ClusterWithdrawn_OrderBy["ClusterValidatorCount"] = "cluster_validatorCount";
    ClusterWithdrawn_OrderBy["Id"] = "id";
    ClusterWithdrawn_OrderBy["OperatorIds"] = "operatorIds";
    ClusterWithdrawn_OrderBy["Owner"] = "owner";
    ClusterWithdrawn_OrderBy["TransactionHash"] = "transactionHash";
    ClusterWithdrawn_OrderBy["Value"] = "value";
})(ClusterWithdrawn_OrderBy || (ClusterWithdrawn_OrderBy = {}));
export var Cluster_OrderBy;
(function (Cluster_OrderBy) {
    Cluster_OrderBy["Active"] = "active";
    Cluster_OrderBy["Balance"] = "balance";
    Cluster_OrderBy["Id"] = "id";
    Cluster_OrderBy["Index"] = "index";
    Cluster_OrderBy["LastUpdateBlockNumber"] = "lastUpdateBlockNumber";
    Cluster_OrderBy["LastUpdateBlockTimestamp"] = "lastUpdateBlockTimestamp";
    Cluster_OrderBy["LastUpdateTransactionHash"] = "lastUpdateTransactionHash";
    Cluster_OrderBy["NetworkFeeIndex"] = "networkFeeIndex";
    Cluster_OrderBy["OperatorIds"] = "operatorIds";
    Cluster_OrderBy["Owner"] = "owner";
    Cluster_OrderBy["OwnerFeeRecipient"] = "owner__feeRecipient";
    Cluster_OrderBy["OwnerId"] = "owner__id";
    Cluster_OrderBy["OwnerNonce"] = "owner__nonce";
    Cluster_OrderBy["OwnerValidatorCount"] = "owner__validatorCount";
    Cluster_OrderBy["ValidatorCount"] = "validatorCount";
    Cluster_OrderBy["Validators"] = "validators";
})(Cluster_OrderBy || (Cluster_OrderBy = {}));
export var DaoUpdateTypes;
(function (DaoUpdateTypes) {
    DaoUpdateTypes["DeclareOperatorFeePeriod"] = "DECLARE_OPERATOR_FEE_PERIOD";
    DaoUpdateTypes["ExecuteOperatorFeePeriod"] = "EXECUTE_OPERATOR_FEE_PERIOD";
    DaoUpdateTypes["Initialization"] = "INITIALIZATION";
    DaoUpdateTypes["LiquidationThreshold"] = "LIQUIDATION_THRESHOLD";
    DaoUpdateTypes["MinLiquidationCollateral"] = "MIN_LIQUIDATION_COLLATERAL";
    DaoUpdateTypes["NetworkFee"] = "NETWORK_FEE";
    DaoUpdateTypes["OperatorAdded"] = "OPERATOR_ADDED";
    DaoUpdateTypes["OperatorFeeIncreaseLimit"] = "OPERATOR_FEE_INCREASE_LIMIT";
    DaoUpdateTypes["OperatorMaxFee"] = "OPERATOR_MAX_FEE";
    DaoUpdateTypes["OperatorRemoved"] = "OPERATOR_REMOVED";
    DaoUpdateTypes["ValidatorAdded"] = "VALIDATOR_ADDED";
    DaoUpdateTypes["ValidatorRemoved"] = "VALIDATOR_REMOVED";
})(DaoUpdateTypes || (DaoUpdateTypes = {}));
export var DaoValues_OrderBy;
(function (DaoValues_OrderBy) {
    DaoValues_OrderBy["DeclareOperatorFeePeriod"] = "declareOperatorFeePeriod";
    DaoValues_OrderBy["ExecuteOperatorFeePeriod"] = "executeOperatorFeePeriod";
    DaoValues_OrderBy["Id"] = "id";
    DaoValues_OrderBy["LastUpdateBlockNumber"] = "lastUpdateBlockNumber";
    DaoValues_OrderBy["LastUpdateBlockTimestamp"] = "lastUpdateBlockTimestamp";
    DaoValues_OrderBy["LastUpdateTransactionHash"] = "lastUpdateTransactionHash";
    DaoValues_OrderBy["LiquidationThreshold"] = "liquidationThreshold";
    DaoValues_OrderBy["MinimumLiquidationCollateral"] = "minimumLiquidationCollateral";
    DaoValues_OrderBy["NetworkFee"] = "networkFee";
    DaoValues_OrderBy["NetworkFeeIndex"] = "networkFeeIndex";
    DaoValues_OrderBy["NetworkFeeIndexBlockNumber"] = "networkFeeIndexBlockNumber";
    DaoValues_OrderBy["OperatorFeeIncreaseLimit"] = "operatorFeeIncreaseLimit";
    DaoValues_OrderBy["OperatorMaximumFee"] = "operatorMaximumFee";
    DaoValues_OrderBy["OperatorsAdded"] = "operatorsAdded";
    DaoValues_OrderBy["OperatorsRemoved"] = "operatorsRemoved";
    DaoValues_OrderBy["TotalAccounts"] = "totalAccounts";
    DaoValues_OrderBy["TotalOperators"] = "totalOperators";
    DaoValues_OrderBy["TotalValidators"] = "totalValidators";
    DaoValues_OrderBy["UpdateType"] = "updateType";
    DaoValues_OrderBy["ValidatorsAdded"] = "validatorsAdded";
    DaoValues_OrderBy["ValidatorsPerOperatorLimit"] = "validatorsPerOperatorLimit";
    DaoValues_OrderBy["ValidatorsRemoved"] = "validatorsRemoved";
})(DaoValues_OrderBy || (DaoValues_OrderBy = {}));
export var DeclareOperatorFeePeriodUpdated_OrderBy;
(function (DeclareOperatorFeePeriodUpdated_OrderBy) {
    DeclareOperatorFeePeriodUpdated_OrderBy["BlockNumber"] = "blockNumber";
    DeclareOperatorFeePeriodUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    DeclareOperatorFeePeriodUpdated_OrderBy["Id"] = "id";
    DeclareOperatorFeePeriodUpdated_OrderBy["TransactionHash"] = "transactionHash";
    DeclareOperatorFeePeriodUpdated_OrderBy["Value"] = "value";
})(DeclareOperatorFeePeriodUpdated_OrderBy || (DeclareOperatorFeePeriodUpdated_OrderBy = {}));
export var ExecuteOperatorFeePeriodUpdated_OrderBy;
(function (ExecuteOperatorFeePeriodUpdated_OrderBy) {
    ExecuteOperatorFeePeriodUpdated_OrderBy["BlockNumber"] = "blockNumber";
    ExecuteOperatorFeePeriodUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ExecuteOperatorFeePeriodUpdated_OrderBy["Id"] = "id";
    ExecuteOperatorFeePeriodUpdated_OrderBy["TransactionHash"] = "transactionHash";
    ExecuteOperatorFeePeriodUpdated_OrderBy["Value"] = "value";
})(ExecuteOperatorFeePeriodUpdated_OrderBy || (ExecuteOperatorFeePeriodUpdated_OrderBy = {}));
export var FeeRecipientAddressUpdated_OrderBy;
(function (FeeRecipientAddressUpdated_OrderBy) {
    FeeRecipientAddressUpdated_OrderBy["BlockNumber"] = "blockNumber";
    FeeRecipientAddressUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    FeeRecipientAddressUpdated_OrderBy["Id"] = "id";
    FeeRecipientAddressUpdated_OrderBy["Owner"] = "owner";
    FeeRecipientAddressUpdated_OrderBy["RecipientAddress"] = "recipientAddress";
    FeeRecipientAddressUpdated_OrderBy["TransactionHash"] = "transactionHash";
})(FeeRecipientAddressUpdated_OrderBy || (FeeRecipientAddressUpdated_OrderBy = {}));
export var LiquidationThresholdPeriodUpdated_OrderBy;
(function (LiquidationThresholdPeriodUpdated_OrderBy) {
    LiquidationThresholdPeriodUpdated_OrderBy["BlockNumber"] = "blockNumber";
    LiquidationThresholdPeriodUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    LiquidationThresholdPeriodUpdated_OrderBy["Id"] = "id";
    LiquidationThresholdPeriodUpdated_OrderBy["TransactionHash"] = "transactionHash";
    LiquidationThresholdPeriodUpdated_OrderBy["Value"] = "value";
})(LiquidationThresholdPeriodUpdated_OrderBy || (LiquidationThresholdPeriodUpdated_OrderBy = {}));
export var MinimumLiquidationCollateralUpdated_OrderBy;
(function (MinimumLiquidationCollateralUpdated_OrderBy) {
    MinimumLiquidationCollateralUpdated_OrderBy["BlockNumber"] = "blockNumber";
    MinimumLiquidationCollateralUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    MinimumLiquidationCollateralUpdated_OrderBy["Id"] = "id";
    MinimumLiquidationCollateralUpdated_OrderBy["TransactionHash"] = "transactionHash";
    MinimumLiquidationCollateralUpdated_OrderBy["Value"] = "value";
})(MinimumLiquidationCollateralUpdated_OrderBy || (MinimumLiquidationCollateralUpdated_OrderBy = {}));
export var NetworkEarningsWithdrawn_OrderBy;
(function (NetworkEarningsWithdrawn_OrderBy) {
    NetworkEarningsWithdrawn_OrderBy["BlockNumber"] = "blockNumber";
    NetworkEarningsWithdrawn_OrderBy["BlockTimestamp"] = "blockTimestamp";
    NetworkEarningsWithdrawn_OrderBy["Id"] = "id";
    NetworkEarningsWithdrawn_OrderBy["Recipient"] = "recipient";
    NetworkEarningsWithdrawn_OrderBy["TransactionHash"] = "transactionHash";
    NetworkEarningsWithdrawn_OrderBy["Value"] = "value";
})(NetworkEarningsWithdrawn_OrderBy || (NetworkEarningsWithdrawn_OrderBy = {}));
export var NetworkFeeUpdated_OrderBy;
(function (NetworkFeeUpdated_OrderBy) {
    NetworkFeeUpdated_OrderBy["BlockNumber"] = "blockNumber";
    NetworkFeeUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    NetworkFeeUpdated_OrderBy["Id"] = "id";
    NetworkFeeUpdated_OrderBy["NewFee"] = "newFee";
    NetworkFeeUpdated_OrderBy["OldFee"] = "oldFee";
    NetworkFeeUpdated_OrderBy["TransactionHash"] = "transactionHash";
})(NetworkFeeUpdated_OrderBy || (NetworkFeeUpdated_OrderBy = {}));
export var OperatorAdded_OrderBy;
(function (OperatorAdded_OrderBy) {
    OperatorAdded_OrderBy["BlockNumber"] = "blockNumber";
    OperatorAdded_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorAdded_OrderBy["Fee"] = "fee";
    OperatorAdded_OrderBy["Id"] = "id";
    OperatorAdded_OrderBy["OperatorId"] = "operatorId";
    OperatorAdded_OrderBy["Owner"] = "owner";
    OperatorAdded_OrderBy["PublicKey"] = "publicKey";
    OperatorAdded_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorAdded_OrderBy || (OperatorAdded_OrderBy = {}));
export var OperatorFeeDeclarationCancelled_OrderBy;
(function (OperatorFeeDeclarationCancelled_OrderBy) {
    OperatorFeeDeclarationCancelled_OrderBy["BlockNumber"] = "blockNumber";
    OperatorFeeDeclarationCancelled_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorFeeDeclarationCancelled_OrderBy["Id"] = "id";
    OperatorFeeDeclarationCancelled_OrderBy["OperatorId"] = "operatorId";
    OperatorFeeDeclarationCancelled_OrderBy["Owner"] = "owner";
    OperatorFeeDeclarationCancelled_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorFeeDeclarationCancelled_OrderBy || (OperatorFeeDeclarationCancelled_OrderBy = {}));
export var OperatorFeeDeclared_OrderBy;
(function (OperatorFeeDeclared_OrderBy) {
    OperatorFeeDeclared_OrderBy["BlockNumber"] = "blockNumber";
    OperatorFeeDeclared_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorFeeDeclared_OrderBy["Fee"] = "fee";
    OperatorFeeDeclared_OrderBy["Id"] = "id";
    OperatorFeeDeclared_OrderBy["OperatorId"] = "operatorId";
    OperatorFeeDeclared_OrderBy["Owner"] = "owner";
    OperatorFeeDeclared_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorFeeDeclared_OrderBy || (OperatorFeeDeclared_OrderBy = {}));
export var OperatorFeeExecuted_OrderBy;
(function (OperatorFeeExecuted_OrderBy) {
    OperatorFeeExecuted_OrderBy["BlockNumber"] = "blockNumber";
    OperatorFeeExecuted_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorFeeExecuted_OrderBy["Fee"] = "fee";
    OperatorFeeExecuted_OrderBy["Id"] = "id";
    OperatorFeeExecuted_OrderBy["OperatorId"] = "operatorId";
    OperatorFeeExecuted_OrderBy["Owner"] = "owner";
    OperatorFeeExecuted_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorFeeExecuted_OrderBy || (OperatorFeeExecuted_OrderBy = {}));
export var OperatorFeeIncreaseLimitUpdated_OrderBy;
(function (OperatorFeeIncreaseLimitUpdated_OrderBy) {
    OperatorFeeIncreaseLimitUpdated_OrderBy["BlockNumber"] = "blockNumber";
    OperatorFeeIncreaseLimitUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorFeeIncreaseLimitUpdated_OrderBy["Id"] = "id";
    OperatorFeeIncreaseLimitUpdated_OrderBy["TransactionHash"] = "transactionHash";
    OperatorFeeIncreaseLimitUpdated_OrderBy["Value"] = "value";
})(OperatorFeeIncreaseLimitUpdated_OrderBy || (OperatorFeeIncreaseLimitUpdated_OrderBy = {}));
export var OperatorMaximumFeeUpdated_OrderBy;
(function (OperatorMaximumFeeUpdated_OrderBy) {
    OperatorMaximumFeeUpdated_OrderBy["BlockNumber"] = "blockNumber";
    OperatorMaximumFeeUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorMaximumFeeUpdated_OrderBy["Id"] = "id";
    OperatorMaximumFeeUpdated_OrderBy["MaxFee"] = "maxFee";
    OperatorMaximumFeeUpdated_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorMaximumFeeUpdated_OrderBy || (OperatorMaximumFeeUpdated_OrderBy = {}));
export var OperatorMultipleWhitelistRemoved_OrderBy;
(function (OperatorMultipleWhitelistRemoved_OrderBy) {
    OperatorMultipleWhitelistRemoved_OrderBy["BlockNumber"] = "blockNumber";
    OperatorMultipleWhitelistRemoved_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorMultipleWhitelistRemoved_OrderBy["Id"] = "id";
    OperatorMultipleWhitelistRemoved_OrderBy["OperatorIds"] = "operatorIds";
    OperatorMultipleWhitelistRemoved_OrderBy["TransactionHash"] = "transactionHash";
    OperatorMultipleWhitelistRemoved_OrderBy["WhitelistAddresses"] = "whitelistAddresses";
})(OperatorMultipleWhitelistRemoved_OrderBy || (OperatorMultipleWhitelistRemoved_OrderBy = {}));
export var OperatorMultipleWhitelistUpdated_OrderBy;
(function (OperatorMultipleWhitelistUpdated_OrderBy) {
    OperatorMultipleWhitelistUpdated_OrderBy["BlockNumber"] = "blockNumber";
    OperatorMultipleWhitelistUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorMultipleWhitelistUpdated_OrderBy["Id"] = "id";
    OperatorMultipleWhitelistUpdated_OrderBy["OperatorIds"] = "operatorIds";
    OperatorMultipleWhitelistUpdated_OrderBy["TransactionHash"] = "transactionHash";
    OperatorMultipleWhitelistUpdated_OrderBy["WhitelistAddresses"] = "whitelistAddresses";
})(OperatorMultipleWhitelistUpdated_OrderBy || (OperatorMultipleWhitelistUpdated_OrderBy = {}));
export var OperatorPrivacyStatusUpdated_OrderBy;
(function (OperatorPrivacyStatusUpdated_OrderBy) {
    OperatorPrivacyStatusUpdated_OrderBy["BlockNumber"] = "blockNumber";
    OperatorPrivacyStatusUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorPrivacyStatusUpdated_OrderBy["Id"] = "id";
    OperatorPrivacyStatusUpdated_OrderBy["OperatorIds"] = "operatorIds";
    OperatorPrivacyStatusUpdated_OrderBy["ToPrivate"] = "toPrivate";
    OperatorPrivacyStatusUpdated_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorPrivacyStatusUpdated_OrderBy || (OperatorPrivacyStatusUpdated_OrderBy = {}));
export var OperatorRemoved_OrderBy;
(function (OperatorRemoved_OrderBy) {
    OperatorRemoved_OrderBy["BlockNumber"] = "blockNumber";
    OperatorRemoved_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorRemoved_OrderBy["Id"] = "id";
    OperatorRemoved_OrderBy["OperatorId"] = "operatorId";
    OperatorRemoved_OrderBy["TransactionHash"] = "transactionHash";
})(OperatorRemoved_OrderBy || (OperatorRemoved_OrderBy = {}));
export var OperatorWhitelistUpdated_OrderBy;
(function (OperatorWhitelistUpdated_OrderBy) {
    OperatorWhitelistUpdated_OrderBy["BlockNumber"] = "blockNumber";
    OperatorWhitelistUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorWhitelistUpdated_OrderBy["Id"] = "id";
    OperatorWhitelistUpdated_OrderBy["OperatorId"] = "operatorId";
    OperatorWhitelistUpdated_OrderBy["TransactionHash"] = "transactionHash";
    OperatorWhitelistUpdated_OrderBy["Whitelisted"] = "whitelisted";
})(OperatorWhitelistUpdated_OrderBy || (OperatorWhitelistUpdated_OrderBy = {}));
export var OperatorWhitelistingContractUpdated_OrderBy;
(function (OperatorWhitelistingContractUpdated_OrderBy) {
    OperatorWhitelistingContractUpdated_OrderBy["BlockNumber"] = "blockNumber";
    OperatorWhitelistingContractUpdated_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorWhitelistingContractUpdated_OrderBy["Id"] = "id";
    OperatorWhitelistingContractUpdated_OrderBy["OperatorIds"] = "operatorIds";
    OperatorWhitelistingContractUpdated_OrderBy["TransactionHash"] = "transactionHash";
    OperatorWhitelistingContractUpdated_OrderBy["WhitelistingContract"] = "whitelistingContract";
})(OperatorWhitelistingContractUpdated_OrderBy || (OperatorWhitelistingContractUpdated_OrderBy = {}));
export var OperatorWithdrawn_OrderBy;
(function (OperatorWithdrawn_OrderBy) {
    OperatorWithdrawn_OrderBy["BlockNumber"] = "blockNumber";
    OperatorWithdrawn_OrderBy["BlockTimestamp"] = "blockTimestamp";
    OperatorWithdrawn_OrderBy["Id"] = "id";
    OperatorWithdrawn_OrderBy["OperatorId"] = "operatorId";
    OperatorWithdrawn_OrderBy["Owner"] = "owner";
    OperatorWithdrawn_OrderBy["TransactionHash"] = "transactionHash";
    OperatorWithdrawn_OrderBy["Value"] = "value";
})(OperatorWithdrawn_OrderBy || (OperatorWithdrawn_OrderBy = {}));
export var Operator_OrderBy;
(function (Operator_OrderBy) {
    Operator_OrderBy["DeclaredFee"] = "declaredFee";
    Operator_OrderBy["Fee"] = "fee";
    Operator_OrderBy["FeeIndex"] = "feeIndex";
    Operator_OrderBy["FeeIndexBlockNumber"] = "feeIndexBlockNumber";
    Operator_OrderBy["Id"] = "id";
    Operator_OrderBy["IsPrivate"] = "isPrivate";
    Operator_OrderBy["LastUpdateBlockNumber"] = "lastUpdateBlockNumber";
    Operator_OrderBy["LastUpdateBlockTimestamp"] = "lastUpdateBlockTimestamp";
    Operator_OrderBy["LastUpdateTransactionHash"] = "lastUpdateTransactionHash";
    Operator_OrderBy["OperatorId"] = "operatorId";
    Operator_OrderBy["Owner"] = "owner";
    Operator_OrderBy["OwnerFeeRecipient"] = "owner__feeRecipient";
    Operator_OrderBy["OwnerId"] = "owner__id";
    Operator_OrderBy["OwnerNonce"] = "owner__nonce";
    Operator_OrderBy["OwnerValidatorCount"] = "owner__validatorCount";
    Operator_OrderBy["PublicKey"] = "publicKey";
    Operator_OrderBy["Removed"] = "removed";
    Operator_OrderBy["TotalWithdrawn"] = "totalWithdrawn";
    Operator_OrderBy["ValidatorCount"] = "validatorCount";
    Operator_OrderBy["Validators"] = "validators";
    Operator_OrderBy["Whitelisted"] = "whitelisted";
    Operator_OrderBy["WhitelistedContract"] = "whitelistedContract";
})(Operator_OrderBy || (Operator_OrderBy = {}));
/** Defines the order direction, either ascending or descending */
export var OrderDirection;
(function (OrderDirection) {
    OrderDirection["Asc"] = "asc";
    OrderDirection["Desc"] = "desc";
})(OrderDirection || (OrderDirection = {}));
export var ValidatorAdded_OrderBy;
(function (ValidatorAdded_OrderBy) {
    ValidatorAdded_OrderBy["BlockNumber"] = "blockNumber";
    ValidatorAdded_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ValidatorAdded_OrderBy["ClusterActive"] = "cluster_active";
    ValidatorAdded_OrderBy["ClusterBalance"] = "cluster_balance";
    ValidatorAdded_OrderBy["ClusterIndex"] = "cluster_index";
    ValidatorAdded_OrderBy["ClusterNetworkFeeIndex"] = "cluster_networkFeeIndex";
    ValidatorAdded_OrderBy["ClusterValidatorCount"] = "cluster_validatorCount";
    ValidatorAdded_OrderBy["Id"] = "id";
    ValidatorAdded_OrderBy["OperatorIds"] = "operatorIds";
    ValidatorAdded_OrderBy["Owner"] = "owner";
    ValidatorAdded_OrderBy["PublicKey"] = "publicKey";
    ValidatorAdded_OrderBy["Shares"] = "shares";
    ValidatorAdded_OrderBy["TransactionHash"] = "transactionHash";
})(ValidatorAdded_OrderBy || (ValidatorAdded_OrderBy = {}));
export var ValidatorRemoved_OrderBy;
(function (ValidatorRemoved_OrderBy) {
    ValidatorRemoved_OrderBy["BlockNumber"] = "blockNumber";
    ValidatorRemoved_OrderBy["BlockTimestamp"] = "blockTimestamp";
    ValidatorRemoved_OrderBy["ClusterActive"] = "cluster_active";
    ValidatorRemoved_OrderBy["ClusterBalance"] = "cluster_balance";
    ValidatorRemoved_OrderBy["ClusterIndex"] = "cluster_index";
    ValidatorRemoved_OrderBy["ClusterNetworkFeeIndex"] = "cluster_networkFeeIndex";
    ValidatorRemoved_OrderBy["ClusterValidatorCount"] = "cluster_validatorCount";
    ValidatorRemoved_OrderBy["Id"] = "id";
    ValidatorRemoved_OrderBy["OperatorIds"] = "operatorIds";
    ValidatorRemoved_OrderBy["Owner"] = "owner";
    ValidatorRemoved_OrderBy["PublicKey"] = "publicKey";
    ValidatorRemoved_OrderBy["TransactionHash"] = "transactionHash";
})(ValidatorRemoved_OrderBy || (ValidatorRemoved_OrderBy = {}));
export var Validator_OrderBy;
(function (Validator_OrderBy) {
    Validator_OrderBy["Cluster"] = "cluster";
    Validator_OrderBy["ClusterActive"] = "cluster__active";
    Validator_OrderBy["ClusterBalance"] = "cluster__balance";
    Validator_OrderBy["ClusterId"] = "cluster__id";
    Validator_OrderBy["ClusterIndex"] = "cluster__index";
    Validator_OrderBy["ClusterLastUpdateBlockNumber"] = "cluster__lastUpdateBlockNumber";
    Validator_OrderBy["ClusterLastUpdateBlockTimestamp"] = "cluster__lastUpdateBlockTimestamp";
    Validator_OrderBy["ClusterLastUpdateTransactionHash"] = "cluster__lastUpdateTransactionHash";
    Validator_OrderBy["ClusterNetworkFeeIndex"] = "cluster__networkFeeIndex";
    Validator_OrderBy["ClusterValidatorCount"] = "cluster__validatorCount";
    Validator_OrderBy["Id"] = "id";
    Validator_OrderBy["LastUpdateBlockNumber"] = "lastUpdateBlockNumber";
    Validator_OrderBy["LastUpdateBlockTimestamp"] = "lastUpdateBlockTimestamp";
    Validator_OrderBy["LastUpdateTransactionHash"] = "lastUpdateTransactionHash";
    Validator_OrderBy["Operators"] = "operators";
    Validator_OrderBy["Owner"] = "owner";
    Validator_OrderBy["OwnerFeeRecipient"] = "owner__feeRecipient";
    Validator_OrderBy["OwnerId"] = "owner__id";
    Validator_OrderBy["OwnerNonce"] = "owner__nonce";
    Validator_OrderBy["OwnerValidatorCount"] = "owner__validatorCount";
    Validator_OrderBy["Removed"] = "removed";
    Validator_OrderBy["Shares"] = "shares";
})(Validator_OrderBy || (Validator_OrderBy = {}));
export var _SubgraphErrorPolicy_;
(function (_SubgraphErrorPolicy_) {
    /** Data will be returned even if the subgraph has indexing errors */
    _SubgraphErrorPolicy_["Allow"] = "allow";
    /** If the subgraph has indexing errors, data will be omitted. The default. */
    _SubgraphErrorPolicy_["Deny"] = "deny";
})(_SubgraphErrorPolicy_ || (_SubgraphErrorPolicy_ = {}));
export const GetClusterSnapshotDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetClusterSnapshot" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "cluster" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "active" } }, { "kind": "Field", "name": { "kind": "Name", "value": "validatorCount" } }, { "kind": "Field", "name": { "kind": "Name", "value": "balance" } }, { "kind": "Field", "name": { "kind": "Name", "value": "index" } }, { "kind": "Field", "name": { "kind": "Name", "value": "networkFeeIndex" } }] } }] } }] };
export const GetClusterDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetCluster" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "cluster" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "active" } }, { "kind": "Field", "name": { "kind": "Name", "value": "validatorCount" } }, { "kind": "Field", "name": { "kind": "Name", "value": "balance" } }, { "kind": "Field", "name": { "kind": "Name", "value": "index" } }, { "kind": "Field", "name": { "kind": "Name", "value": "networkFeeIndex" } }, { "kind": "Field", "name": { "kind": "Name", "value": "operatorIds" } }] } }] } }] };
export const GetClustersDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetClusters" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "owner" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "String" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "clusters" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "where" }, "value": { "kind": "ObjectValue", "fields": [{ "kind": "ObjectField", "name": { "kind": "Name", "value": "owner" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "owner" } } }] } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }, { "kind": "Field", "name": { "kind": "Name", "value": "active" } }, { "kind": "Field", "name": { "kind": "Name", "value": "validatorCount" } }, { "kind": "Field", "name": { "kind": "Name", "value": "balance" } }, { "kind": "Field", "name": { "kind": "Name", "value": "index" } }, { "kind": "Field", "name": { "kind": "Name", "value": "networkFeeIndex" } }, { "kind": "Field", "name": { "kind": "Name", "value": "operatorIds" } }] } }] } }] };
export const GetOwnerNonceDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetOwnerNonce" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "owner" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "account" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "owner" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "nonce" } }] } }] } }] };
export const GetOwnerNonceByBlockDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetOwnerNonceByBlock" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "owner" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }, { "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "block" } }, "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "Int" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "account" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "owner" } } }, { "kind": "Argument", "name": { "kind": "Name", "value": "block" }, "value": { "kind": "ObjectValue", "fields": [{ "kind": "ObjectField", "name": { "kind": "Name", "value": "number" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "block" } } }] } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "nonce" } }] } }] } }] };
export const GetOperatorDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetOperator" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "operator" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }, { "kind": "Field", "name": { "kind": "Name", "value": "publicKey" } }, { "kind": "Field", "name": { "kind": "Name", "value": "validatorCount" } }, { "kind": "Field", "name": { "kind": "Name", "value": "isPrivate" } }, { "kind": "Field", "name": { "kind": "Name", "value": "whitelistedContract" } }, { "kind": "Field", "name": { "kind": "Name", "value": "whitelisted" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }] } }] } }] } }] };
export const GetOperatorsDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetOperators" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "operatorIds" } }, "type": { "kind": "NonNullType", "type": { "kind": "ListType", "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "String" } } } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "operators" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "where" }, "value": { "kind": "ObjectValue", "fields": [{ "kind": "ObjectField", "name": { "kind": "Name", "value": "id_in" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "operatorIds" } } }] } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }, { "kind": "Field", "name": { "kind": "Name", "value": "publicKey" } }, { "kind": "Field", "name": { "kind": "Name", "value": "validatorCount" } }, { "kind": "Field", "name": { "kind": "Name", "value": "isPrivate" } }, { "kind": "Field", "name": { "kind": "Name", "value": "whitelistedContract" } }, { "kind": "Field", "name": { "kind": "Name", "value": "whitelisted" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }] } }] } }] } }] };
export const GetValidatorsDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetValidators" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "ids" } }, "type": { "kind": "NonNullType", "type": { "kind": "ListType", "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "Bytes" } } } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "validators" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "where" }, "value": { "kind": "ObjectValue", "fields": [{ "kind": "ObjectField", "name": { "kind": "Name", "value": "id_in" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "ids" } } }] } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }] } }] } }] };
export const GetValidatorDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetValidator" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "validator" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "id" } }] } }] } }] };
export const GetClusterBalanceDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "GetClusterBalance" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "clusterId" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }, { "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "daoAddress" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }, { "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "operatorIds" } }, "type": { "kind": "NonNullType", "type": { "kind": "ListType", "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "String" } } } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "_meta" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "block" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "number" } }] } }] } }, { "kind": "Field", "name": { "kind": "Name", "value": "daovalues" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "daoAddress" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "networkFee" } }, { "kind": "Field", "name": { "kind": "Name", "value": "networkFeeIndex" } }, { "kind": "Field", "name": { "kind": "Name", "value": "networkFeeIndexBlockNumber" } }, { "kind": "Field", "name": { "kind": "Name", "value": "liquidationThreshold" } }, { "kind": "Field", "name": { "kind": "Name", "value": "minimumLiquidationCollateral" } }] } }, { "kind": "Field", "name": { "kind": "Name", "value": "operators" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "where" }, "value": { "kind": "ObjectValue", "fields": [{ "kind": "ObjectField", "name": { "kind": "Name", "value": "id_in" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "operatorIds" } } }] } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "fee" } }, { "kind": "Field", "name": { "kind": "Name", "value": "feeIndex" } }, { "kind": "Field", "name": { "kind": "Name", "value": "feeIndexBlockNumber" } }] } }, { "kind": "Field", "name": { "kind": "Name", "value": "cluster" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "id" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "clusterId" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "validatorCount" } }, { "kind": "Field", "name": { "kind": "Name", "value": "networkFeeIndex" } }, { "kind": "Field", "name": { "kind": "Name", "value": "index" } }, { "kind": "Field", "name": { "kind": "Name", "value": "balance" } }] } }] } }] };
