// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SSVStorage$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SSVStorage",
  "sourceName": "contracts/libraries/SSVStorage.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212206b62334ea277c9c9971778e2fb3f9732a2a60b40414e70bc8309eace6dcb1b0e64736f6c63430008180033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212206b62334ea277c9c9971778e2fb3f9732a2a60b40414e70bc8309eace6dcb1b0e64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SSVStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SSVStorage$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/libraries/SSVStorage.sol:SSVStorage",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SSVStorage$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SSVStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SSVStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/libraries/SSVStorage.sol:SSVStorage",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SSVStorage$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SSVStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SSVStorage$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/libraries/SSVStorage.sol:SSVStorage",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SSVStorage$Type["abi"]>>;
}
