// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISSVClusters$Type } from "./ISSVClusters";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISSVClusters"]: ISSVClusters$Type;
    ["contracts/interfaces/ISSVClusters.sol:ISSVClusters"]: ISSVClusters$Type;
  }

  interface ContractTypesMap {
    ["ISSVClusters"]: GetContractReturnType<ISSVClusters$Type["abi"]>;
    ["contracts/interfaces/ISSVClusters.sol:ISSVClusters"]: GetContractReturnType<ISSVClusters$Type["abi"]>;
  }
}
